apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: azure-bus-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  externalSecretName: "azure-bus-es"
  namespaceSelector:
    matchLabels: 
      secrets: azure-bus
  refreshTime: "15s" # How often this secret is synchronized
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      name: secret-store
      kind: ClusterSecretStore
    target: # Our target Kubernetes Secret
      name: connection-string # If not present, then the secretKey field under data will be used
      creationPolicy: Owner # This will create the secret if it doesn't exist
    data:
      - secretKey: connection
        remoteRef:
          key: connection-string # This is the remote key in the secret provider (might change in meaning based on your provider)