kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: openshift-gitops-weaviate-extended-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-priviledged-scc
  # name: openshift-gitops-argocd-extended-clusterrole
subjects:
  - kind: ServiceAccount
    name: default
    namespace: weaviate
  - kind: ServiceAccount
    name: deployer
    namespace: weaviate