apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
  namespace: hello-chris
spec:
  secretTargetRef:
    - key: connection
      name: connection-string # name of secret
      parameter: connection # key in secret