apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azure-bus-trigger
  namespace: hello-chris
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: pop-queue
          image: quay.io/cnuland/azure-pop-queue:v5
          command: ["python",  "pop-queue.py"]
          env:
          - name: WEAVIATE_URL
            value: "https://weaviate-weaviate.apps.i20vwjms.eastus.aroapp.io/"
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: connection-string
                key: connection
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: weaviate-api
                key: token
        restartPolicy: OnFailure 
    backoffLimit: 4  
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: test
      messageCount: "1"
    authenticationRef:
        # reference to TriggerAuthentication
        name: azure-servicebus-auth