apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
  namespace: hello-chris
  labels:
     app.kubernetes.io/instance: hello-chris
spec:
  secretTargetRef:
    - key: connection
      name: connection-string # name of secret
      parameter: connection-string # key in secret