apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- infra/pipelines.yaml
- infra/keda.yaml
- app/hello-chris.yaml
- argocd.yaml
- infra/onboarding.yaml
- rbac/cluster-role-gitops.yaml
- rbac/cluster-rolebinding-gitops.yaml
- rbac/cluster-role-priviledged.yaml